version: 2

jobs:

  frontend1_deploy:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py && sudo apt-get update
      - run: sudo apt-get install python3-dev python3-pip
      - run: sudo pip3 install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: yarn run deploy

  frontend2_deploy:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py && sudo apt-get update
      - run: sudo apt-get install python3-dev python3-pip
      - run: sudo pip3 install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: yarn run deploy

  test_deploy1:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo ls -al

  test_deploy2:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo pwd

workflows:
  version: 2

  build-deploy:
    jobs:
      - test_deploy1
      - test_deploy2:
          requires:
            - test_deploy1
          filters:
            branches:
              only: master