version: 2

jobs:

  frontend1_deploy:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend1/package.json" }}
          - v1-dependencies-
      - run:
          command: yarn install
          working_directory: ~/repo/frontend1
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "frontend1/package.json" }}
      - run:
          name: Install Python3 and Pip3
          command: |
                sudo curl -O https://bootstrap.pypa.io/get-pip.py && sudo apt-get update
                sudo apt-get install python3-dev python3-pip
          working_directory: ~/repo/frontend1
      - run:
          name: Install awscli
          command: |
                sudo pip3 install awscli --upgrade
                aws --version
          working_directory: ~/repo/frontend1
      - run:
          name: Check and deploy S3 bucket
          command: |
                aws s3 ls
                yarn run deploy
          working_directory: ~/repo/frontend1

  frontend2_deploy:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "frontend2/package.json" }}
          - v1-dependencies-
      - run:
          command: yarn install
          working_directory: ~/repo/frontend2
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "frontend2/package.json" }}
      - run:
          name: Install Python3 and Pip3
          command: |
                sudo curl -O https://bootstrap.pypa.io/get-pip.py && sudo apt-get update
                sudo apt-get install python3-dev python3-pip
          working_directory: ~/repo/frontend2
      - run:
          name: Install awscli
          command: |
                sudo pip3 install awscli --upgrade
                aws --version
          working_directory: ~/repo/frontend2
      - run:
          name: Check and deploy S3 bucket
          command: |
                aws s3 ls
                yarn run deploy
          working_directory: ~/repo/frontend2

workflows:
  version: 2

  build-deploy:
    jobs:
      - frontend1_deploy:
          filters:
            branches:
              only: master
      - frontend2_deploy:
          filters:
            branches:
              only: master